import { StyleSheet } from 'react-native';
import { colors, radii, spacing, typography } from '@daloa/ui';

export const annuaireStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.grey[50],
  },
  headerControls: {
    backgroundColor: colors.bg.surface,
    paddingHorizontal: spacing[4],
    paddingTop: spacing[2],
    paddingBottom: spacing[3],
    borderBottomWidth: 1,
    borderBottomColor: colors.bg.subtle,
    gap: 10,
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  searchInputWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.bg.subtle,
    borderRadius: radii.xl,
    paddingHorizontal: 12,
    height: 42,
    gap: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 13,
    color: colors.text.DEFAULT,
    fontFamily: typography.families.medium,
  },
  filterBtn: {
    width: 42,
    height: 42,
    borderRadius: radii.xl,
    backgroundColor: colors.bg.subtle,
    alignItems: 'center',
    justifyContent: 'center',
  },
  viewToggleGroup: {
    flexDirection: 'row',
    backgroundColor: colors.bg.subtle,
    borderRadius: radii.xl,
    padding: 3,
    gap: 2,
  },
  toggleBtn: {
    width: 34,
    height: 34,
    borderRadius: radii.lg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  toggleBtnActive: {
    backgroundColor: colors.bg.surface,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 1,
  },
  chipsScroll: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 2,
  },
  filterChip: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: radii.full,
    backgroundColor: colors.bg.subtle,
  },
  filterChipActive: {
    backgroundColor: colors.primary.DEFAULT,
  },
  filterChipText: {
    fontSize: 12,
    fontFamily: typography.families.bold,
    color: colors.grey[600],
  },
  filterChipTextActive: {
    color: colors.text.inverse,
  },
  counterRow: {
    paddingHorizontal: spacing[4],
    paddingTop: spacing[3],
    paddingBottom: 6,
  },
  counterText: {
    fontSize: 11,
    fontFamily: typography.families.extrabold,
    color: colors.text.muted,
    letterSpacing: 0.5,
    fontVariant: ['tabular-nums'],
  },
  listContent: {
    paddingTop: spacing[1],
    paddingBottom: 24,
  },
  loadingBox: {
    padding: spacing[8],
    alignItems: 'center',
    gap: 8,
  },
  loadingText: {
    fontSize: 12,
    color: colors.text.muted,
  },
  emptyBox: {
    backgroundColor: colors.bg.surface,
    borderRadius: radii['2xl'],
    padding: spacing[8],
    marginHorizontal: spacing[4],
    marginTop: spacing[4],
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: colors.border.DEFAULT,
    borderStyle: 'dashed',
  },
  emptyTitle: {
    fontSize: 14,
    fontFamily: typography.families.bold,
    color: colors.text.body,
    marginTop: 4,
  },
  emptyDesc: {
    fontSize: 12,
    color: colors.text.muted,
    textAlign: 'center',
  },
});
