import { StyleSheet } from 'react-native';
import { colors, radii, typography } from '@daloa/ui';

export const earningsStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bg.surface,
  },
  loadingCenter: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.bg.surface,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.bg.subtle,
    gap: 10,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: radii.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.bg.subtle,
  },
  headerTitle: {
    fontSize: 18,
    fontFamily: typography.families.black,
    color: colors.text.DEFAULT,
    flex: 1,
  },
  scrollContent: {
    padding: 14,
    backgroundColor: colors.bg.DEFAULT,
  },
  kpiRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 14,
  },
  kpiCard: {
    flex: 1,
    backgroundColor: colors.bg.surface,
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: colors.border.DEFAULT,
    padding: 12,
  },
  kpiIconWrapper: {
    width: 30,
    height: 30,
    borderRadius: radii.md,
    backgroundColor: colors.primary[50],
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  kpiLabel: {
    fontSize: 11,
    fontFamily: typography.families.semibold,
    color: colors.grey[500],
  },
  kpiValue: {
    fontSize: 16,
    fontFamily: typography.families.black,
    color: colors.primary[600],
    marginTop: 2,
  },
  card: {
    backgroundColor: colors.bg.surface,
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: colors.border.DEFAULT,
    padding: 14,
    marginBottom: 14,
  },
  cardTitle: {
    fontSize: 13.5,
    fontFamily: typography.families.extrabold,
    color: colors.text.DEFAULT,
    marginBottom: 10,
  },
  payoutAccountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: colors.grey[50],
    borderRadius: radii.lg,
    padding: 10,
    borderWidth: 1,
    borderColor: colors.border.DEFAULT,
  },
  payoutAccountIcon: {
    width: 36,
    height: 36,
    borderRadius: radii.md,
    backgroundColor: colors.primary[50],
    alignItems: 'center',
    justifyContent: 'center',
  },
  networkName: {
    fontSize: 13,
    fontFamily: typography.families.extrabold,
    color: colors.text.DEFAULT,
  },
  phoneText: {
    fontSize: 11.5,
    color: colors.grey[500],
  },
  modifyBtn: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: colors.bg.surface,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border.DEFAULT,
  },
  modifyBtnText: {
    fontSize: 11.5,
    fontFamily: typography.families.bold,
    color: colors.grey[700],
  },
  setupPrompt: {
    padding: 12,
    backgroundColor: colors.primary[50],
    borderWidth: 1,
    borderColor: colors.primary[100],
    borderRadius: radii.lg,
    alignItems: 'center',
  },
  setupPromptText: {
    fontSize: 12.5,
    fontFamily: typography.families.extrabold,
    color: colors.primary[700],
  },
  sectionHeading: {
    fontSize: 13,
    fontFamily: typography.families.extrabold,
    color: colors.grey[600],
    marginBottom: 8,
    marginLeft: 2,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  payoutItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 10,
  },
  payoutItemBorder: {
    borderTopWidth: 1,
    borderTopColor: colors.bg.subtle,
  },
  payoutIcon: {
    width: 32,
    height: 32,
    borderRadius: radii.md,
    backgroundColor: colors.primary[50],
    alignItems: 'center',
    justifyContent: 'center',
  },
  payoutAmount: {
    fontSize: 13.5,
    fontFamily: typography.families.extrabold,
    color: colors.text.DEFAULT,
  },
  payoutDate: {
    fontSize: 11,
    color: colors.grey[400],
  },
  payoutStatusBadge: {
    backgroundColor: colors.status.successLight,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: radii.full,
  },
  payoutStatusText: {
    fontSize: 10.5,
    fontFamily: typography.families.extrabold,
    color: '#059669',
  },
  emptyPayouts: {
    paddingVertical: 14,
    alignItems: 'center',
  },
  emptyPayoutsText: {
    fontSize: 12.5,
    color: colors.grey[400],
  },
});
