import { StyleSheet } from 'react-native';
import { colors, radii } from '@daloa/ui';

export const earningsStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  loadingCenter: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
    gap: 10,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: radii.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F3F4F6',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#111827',
    flex: 1,
  },
  scrollContent: {
    padding: 14,
    backgroundColor: '#F8F9FA',
  },
  kpiRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 14,
  },
  kpiCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 12,
  },
  kpiIconWrapper: {
    width: 30,
    height: 30,
    borderRadius: radii.md,
    backgroundColor: '#FFF4E6',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  kpiLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.grey[500],
  },
  kpiValue: {
    fontSize: 16,
    fontWeight: '900',
    color: colors.primary[600],
    marginTop: 2,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 14,
    marginBottom: 14,
  },
  cardTitle: {
    fontSize: 13.5,
    fontWeight: '800',
    color: '#111827',
    marginBottom: 10,
  },
  payoutAccountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#F9FAFB',
    borderRadius: radii.lg,
    padding: 10,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  payoutAccountIcon: {
    width: 36,
    height: 36,
    borderRadius: radii.md,
    backgroundColor: '#FFF4E6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  networkName: {
    fontSize: 13,
    fontWeight: '800',
    color: '#111827',
  },
  phoneText: {
    fontSize: 11.5,
    color: colors.grey[500],
  },
  modifyBtn: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: '#FFFFFF',
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  modifyBtnText: {
    fontSize: 11.5,
    fontWeight: '700',
    color: colors.grey[700],
  },
  setupPrompt: {
    padding: 12,
    backgroundColor: '#FFF4E6',
    borderWidth: 1,
    borderColor: '#FFE0B2',
    borderRadius: radii.lg,
    alignItems: 'center',
  },
  setupPromptText: {
    fontSize: 12.5,
    fontWeight: '800',
    color: colors.primary[700],
  },
  sectionHeading: {
    fontSize: 13,
    fontWeight: '800',
    color: colors.grey[600],
    marginBottom: 8,
    marginLeft: 2,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  payoutItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 10,
  },
  payoutItemBorder: {
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
  },
  payoutIcon: {
    width: 32,
    height: 32,
    borderRadius: radii.md,
    backgroundColor: '#FFF4E6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  payoutAmount: {
    fontSize: 13.5,
    fontWeight: '800',
    color: '#111827',
  },
  payoutDate: {
    fontSize: 11,
    color: colors.grey[400],
  },
  payoutStatusBadge: {
    backgroundColor: '#ECFDF5',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: radii.full,
  },
  payoutStatusText: {
    fontSize: 10.5,
    fontWeight: '800',
    color: '#059669',
  },
  emptyPayouts: {
    paddingVertical: 14,
    alignItems: 'center',
  },
  emptyPayoutsText: {
    fontSize: 12.5,
    color: colors.grey[400],
  },
});
