import { StyleSheet } from 'react-native';
import { colors, radii, spacing, typography } from '@daloa/ui';

export const profileStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.grey[50],
  },
  scrollContent: {
    paddingBottom: 40,
  },
  flex1: {
    flex: 1,
  },
  kycCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.primary[50],
    marginHorizontal: spacing[4],
    marginTop: spacing[4],
    padding: spacing[4],
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: colors.primary[100],
    gap: spacing[3],
  },
  kycIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.bg.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionHeader: {
    marginHorizontal: spacing[4],
    marginTop: spacing[6],
    marginBottom: spacing[2],
    letterSpacing: 0.8,
  },
  cardGroup: {
    backgroundColor: colors.bg.surface,
    marginHorizontal: spacing[4],
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: colors.bg.subtle,
    overflow: 'hidden',
  },
  menuRow: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: spacing[4],
    gap: spacing[3],
  },
  borderBottom: {
    borderBottomWidth: 1,
    borderBottomColor: colors.bg.subtle,
  },
  menuIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
  },
  adminBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FAF5FF',
    marginHorizontal: spacing[4],
    padding: spacing[3],
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: '#F3E8FF',
    gap: spacing[3],
  },
  logoutBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.bg.surface,
    marginHorizontal: spacing[4],
    marginTop: spacing[6],
    marginBottom: spacing[4],
    paddingVertical: spacing[3],
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: '#FEE2E2',
    gap: spacing[2],
  },
  /* ── Cartes de synthèse, comme le profil web (Note / Livraisons / Quartiers) ── */
  statsRow: {
    flexDirection: 'row',
    gap: spacing[2],
    paddingHorizontal: spacing[4],
    marginTop: -22,
    marginBottom: spacing[2],
  },
  statCard: {
    flex: 1,
    backgroundColor: colors.bg.surface,
    borderRadius: radii['2xl'],
    paddingVertical: spacing[3],
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border.subtle,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  statValue: {
    fontSize: 21,
    fontFamily: typography.families.black,
    lineHeight: 23,
  },
  statLabel: {
    fontSize: 9.5,
    fontFamily: typography.families.extrabold,
    color: colors.text.muted,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginTop: 5,
  },
  emailCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[3],
    backgroundColor: colors.bg.surface,
    borderRadius: radii['2xl'],
    padding: spacing[4],
    borderWidth: 1,
    borderColor: colors.border.subtle,
    marginTop: spacing[3],
  },
});
