import { StyleSheet } from 'react-native';
import { colors, radii, spacing, typography } from '@daloa/ui';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.grey[50],
  },
  scrollContent: {
    paddingBottom: 24,
  },
  unauthContent: {
    paddingBottom: 32,
  },
  unauthHero: {
    paddingTop: spacing[5],
    paddingHorizontal: spacing[4],
    paddingBottom: 28,
    borderBottomLeftRadius: 36,
    borderBottomRightRadius: 36,
    alignItems: 'center',
    textAlign: 'center',
  },
  unauthIconCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: colors.bg.surface,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing[3],
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  unauthHeroTitle: {
    fontSize: 22,
    fontFamily: typography.families.black,
    color: colors.text.inverse,
    textAlign: 'center',
    lineHeight: 28,
  },
  unauthHeroSub: {
    fontSize: 12.5,
    color: colors.primary[100],
    textAlign: 'center',
    marginTop: 6,
    lineHeight: 18,
    paddingHorizontal: spacing[2],
  },
  perksCard: {
    backgroundColor: colors.bg.surface,
    borderRadius: radii['2xl'],
    marginHorizontal: spacing[4],
    marginTop: -20,
    padding: spacing[4],
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
    borderWidth: 1,
    borderColor: colors.bg.subtle,
    gap: 16,
  },
  perksHeader: {
    fontSize: 14,
    fontFamily: typography.families.extrabold,
    color: colors.text.DEFAULT,
  },
  perkRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  perkIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  perkTitle: {
    fontSize: 13,
    fontFamily: typography.families.bold,
    color: colors.text.DEFAULT,
  },
  perkDesc: {
    fontSize: 11.5,
    color: colors.text.muted,
    marginTop: 2,
    lineHeight: 16,
  },
  actionButtonsWrap: {
    marginTop: spacing[2],
  },
  quickNavSection: {
    marginTop: spacing[4],
    paddingHorizontal: spacing[4],
    gap: 10,
  },
  sectionTitle: {
    fontSize: 11,
    fontFamily: typography.families.black,
    color: colors.text.muted,
    letterSpacing: 0.6,
    marginBottom: 4,
  },
  navRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.bg.surface,
    borderRadius: radii.xl,
    padding: spacing[3],
    borderWidth: 1,
    borderColor: colors.bg.subtle,
    gap: 12,
  },
  navIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navTitle: {
    fontSize: 13.5,
    fontFamily: typography.families.bold,
    color: colors.text.DEFAULT,
  },
  navSub: {
    fontSize: 11.5,
    color: colors.text.muted,
    marginTop: 1,
  },
  missingProfileCard: {
    backgroundColor: '#FFF7ED',
    borderWidth: 1,
    borderColor: '#FFEDD5',
    borderRadius: radii.xl,
    padding: spacing[4],
    marginHorizontal: spacing[4],
    marginTop: spacing[4],
    gap: 8,
  },
  missingProfileTitle: {
    fontSize: 15,
    fontFamily: typography.families.extrabold,
    color: '#C2410C',
  },
  missingProfileSub: {
    fontSize: 12.5,
    color: '#9A3412',
    lineHeight: 18,
  },
  missingProfileBtn: {
    marginTop: 6,
  },
  adminBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.status.infoLight,
    borderWidth: 1,
    borderColor: colors.status.infoBorder,
    borderRadius: radii.xl,
    padding: spacing[3],
    marginHorizontal: spacing[4],
    marginTop: spacing[3],
    gap: 12,
  },
  adminBannerTitle: {
    fontSize: 13.5,
    fontFamily: typography.families.extrabold,
    color: '#1E40AF',
  },
  adminBannerSub: {
    fontSize: 11.5,
    color: colors.status.info,
    marginTop: 1,
  },
  payoutWarningCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: colors.status.warningLight,
    borderWidth: 1,
    borderColor: colors.status.warningBorder,
    borderRadius: radii.xl,
    padding: spacing[4],
    marginHorizontal: spacing[4],
    marginTop: spacing[3],
    gap: 12,
  },
  payoutWarningTitle: {
    fontSize: 13.5,
    fontFamily: typography.families.extrabold,
    color: '#92400E',
  },
  payoutWarningSub: {
    fontSize: 11.5,
    color: colors.status.warningDark,
    marginTop: 2,
    lineHeight: 16,
  },
  payoutWarningBtn: {
    marginTop: 8,
    alignSelf: 'flex-start',
    backgroundColor: colors.categories.home.text,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  payoutWarningBtnText: {
    color: colors.text.inverse,
    fontSize: 11.5,
    fontFamily: typography.families.extrabold,
  },
  curfewCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0F172A',
    borderWidth: 1,
    borderColor: '#334155',
    borderRadius: radii.xl,
    padding: spacing[4],
    marginHorizontal: spacing[4],
    marginTop: spacing[3],
    gap: 12,
  },
  curfewTitle: {
    fontSize: 13.5,
    fontFamily: typography.families.extrabold,
    color: '#FBBF24',
  },
  curfewSub: {
    fontSize: 11.5,
    color: '#94A3B8',
    marginTop: 2,
    lineHeight: 16,
  },
  badgePill: {
    backgroundColor: colors.primary.DEFAULT,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
  },
  badgePillText: {
    color: colors.text.inverse,
    fontSize: 11,
    fontFamily: typography.families.black,
  },
  /* ── Console livreur : miroir du tableau de bord web ── */
  dashSection: {
    paddingHorizontal: spacing[4],
  },
  earningsCard: {
    backgroundColor: colors.bg.surface,
    borderRadius: radii['2xl'],
    padding: spacing[4],
    borderWidth: 1,
    borderColor: colors.border.subtle,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: -20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  earningsLabel: {
    fontSize: 10,
    fontFamily: typography.families.extrabold,
    color: colors.text.muted,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginBottom: 4,
  },
  earningsValueRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 5,
  },
  earningsValue: {
    fontSize: 28,
    fontFamily: typography.families.black,
    color: colors.text.DEFAULT,
    fontVariant: ['tabular-nums'],
    lineHeight: 32,
  },
  earningsCurrency: {
    fontSize: 13,
    fontFamily: typography.families.extrabold,
    color: colors.primary.DEFAULT,
    marginBottom: 3,
  },
  detailsBtn: {
    height: 42,
    paddingHorizontal: spacing[3],
    borderRadius: radii.xl,
    backgroundColor: colors.primary[50],
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  detailsBtnText: {
    fontSize: 12,
    fontFamily: typography.families.extrabold,
    color: colors.primary[700],
  },
  statsGrid: {
    flexDirection: 'row',
    gap: spacing[2],
    marginTop: spacing[3],
  },
  statCard: {
    flex: 1,
    backgroundColor: colors.bg.surface,
    borderRadius: radii['2xl'],
    paddingVertical: spacing[3],
    paddingHorizontal: spacing[2],
    borderWidth: 1,
    borderColor: colors.border.subtle,
    alignItems: 'center',
  },
  statIconWrap: {
    width: 34,
    height: 34,
    borderRadius: radii.lg,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  statValue: {
    fontSize: 17,
    fontFamily: typography.families.black,
    color: colors.text.DEFAULT,
    lineHeight: 19,
  },
  statValueSm: {
    fontSize: 13,
    fontFamily: typography.families.black,
    color: colors.text.DEFAULT,
    lineHeight: 17,
  },
  statCaption: {
    fontSize: 9,
    fontFamily: typography.families.extrabold,
    color: colors.text.muted,
    textTransform: 'uppercase',
    marginTop: 4,
    letterSpacing: 0.3,
  },
  runsHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
    marginTop: spacing[5],
    marginBottom: spacing[3],
  },
  runsHeaderTitle: {
    fontSize: 17,
    fontFamily: typography.families.black,
    color: colors.text.DEFAULT,
  },
  runsCountPill: {
    backgroundColor: colors.primary.DEFAULT,
    borderRadius: radii.full,
    paddingHorizontal: 9,
    paddingVertical: 2,
  },
  runsCountText: {
    fontSize: 11,
    fontFamily: typography.families.black,
    color: colors.text.inverse,
  },
  segmented: {
    flexDirection: 'row',
    backgroundColor: colors.grey[200],
    borderRadius: radii.xl,
    padding: 4,
    marginBottom: spacing[4],
  },
  segmentedItem: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 9,
    borderRadius: radii.lg,
  },
  segmentedItemActive: {
    backgroundColor: colors.bg.surface,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 1,
  },
  segmentedText: {
    fontSize: 12,
    fontFamily: typography.families.extrabold,
    color: colors.text.muted,
  },
  segmentedTextActive: {
    color: colors.primary[700],
  },
  emptyRunsCard: {
    backgroundColor: colors.bg.surface,
    borderRadius: radii['2xl'],
    paddingVertical: 36,
    paddingHorizontal: spacing[5],
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: colors.border.subtle,
    alignItems: 'center',
  },
  emptyRunsIcon: {
    width: 62,
    height: 62,
    borderRadius: radii.xl,
    backgroundColor: colors.grey[50],
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing[3],
  },
  emptyRunsTitle: {
    fontSize: 15,
    fontFamily: typography.families.black,
    color: colors.text.DEFAULT,
    marginBottom: 4,
    textAlign: 'center',
  },
  emptyRunsSub: {
    fontSize: 12,
    color: colors.text.muted,
    textAlign: 'center',
    lineHeight: 17,
  },
  emptyRunsBtn: {
    marginTop: spacing[4],
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    paddingHorizontal: spacing[4],
    paddingVertical: 10,
    borderRadius: radii.lg,
    backgroundColor: colors.grey[100],
  },
  emptyRunsBtnText: {
    fontSize: 12,
    fontFamily: typography.families.extrabold,
    color: colors.text.body,
  },
});
