import { StyleSheet } from 'react-native';
import { radii, spacing } from '@daloa/ui';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F9FAFB',
  },
  scrollContent: {
    paddingBottom: 24,
  },
  unauthContent: {
    paddingBottom: 32,
  },
  unauthHero: {
    paddingTop: spacing[5],
    paddingHorizontal: spacing[4],
    paddingBottom: 28,
    borderBottomLeftRadius: 36,
    borderBottomRightRadius: 36,
    alignItems: 'center',
    textAlign: 'center',
  },
  unauthIconCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing[3],
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  unauthHeroTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#FFFFFF',
    textAlign: 'center',
    lineHeight: 28,
  },
  unauthHeroSub: {
    fontSize: 12.5,
    color: '#FFE0B2',
    textAlign: 'center',
    marginTop: 6,
    lineHeight: 18,
    paddingHorizontal: spacing[2],
  },
  perksCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: radii['2xl'],
    marginHorizontal: spacing[4],
    marginTop: -20,
    padding: spacing[4],
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#F3F4F6',
    gap: 16,
  },
  perksHeader: {
    fontSize: 14,
    fontWeight: '800',
    color: '#111827',
  },
  perkRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  perkIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  perkTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#111827',
  },
  perkDesc: {
    fontSize: 11.5,
    color: '#6B7280',
    marginTop: 2,
    lineHeight: 16,
  },
  actionButtonsWrap: {
    marginTop: spacing[2],
  },
  quickNavSection: {
    marginTop: spacing[4],
    paddingHorizontal: spacing[4],
    gap: 10,
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: '900',
    color: '#6B7280',
    letterSpacing: 0.6,
    marginBottom: 4,
  },
  navRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: radii.xl,
    padding: spacing[3],
    borderWidth: 1,
    borderColor: '#F3F4F6',
    gap: 12,
  },
  navIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navTitle: {
    fontSize: 13.5,
    fontWeight: '700',
    color: '#111827',
  },
  navSub: {
    fontSize: 11.5,
    color: '#6B7280',
    marginTop: 1,
  },
  missingProfileCard: {
    backgroundColor: '#FFF7ED',
    borderWidth: 1,
    borderColor: '#FFEDD5',
    borderRadius: radii.xl,
    padding: spacing[4],
    marginHorizontal: spacing[4],
    marginTop: spacing[4],
    gap: 8,
  },
  missingProfileTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#C2410C',
  },
  missingProfileSub: {
    fontSize: 12.5,
    color: '#9A3412',
    lineHeight: 18,
  },
  missingProfileBtn: {
    marginTop: 6,
  },
});
