import { StyleSheet } from 'react-native';
import { colors, radii, spacing, typography } from '@daloa/ui';

export const directoryDetailStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.grey[50],
  },
  centerLoading: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing[6],
  },
  notFoundText: {
    fontSize: 14,
    color: colors.text.muted,
    fontFamily: typography.families.medium,
  },
  scrollContent: {
    paddingBottom: 32,
  },
  heroGradient: {
    paddingTop: spacing[6],
    paddingBottom: 36,
    alignItems: 'center',
    borderBottomLeftRadius: 36,
    borderBottomRightRadius: 36,
  },
  avatarWrapper: {
    position: 'relative',
    marginBottom: spacing[3],
  },
  avatarRing: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: colors.bg.surface,
    padding: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
  },
  avatarImg: {
    width: '100%',
    height: '100%',
    borderRadius: 40,
  },
  avatarFallback: {
    width: '100%',
    height: '100%',
    borderRadius: 40,
    backgroundColor: colors.primary[50],
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarFallbackText: {
    fontSize: 32,
    fontFamily: typography.families.black,
    color: colors.primary[700],
  },
  statusDotLarge: {
    position: 'absolute',
    bottom: 2,
    right: 2,
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 3,
    borderColor: colors.bg.surface,
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  heroName: {
    fontSize: 20,
    fontFamily: typography.families.black,
    color: colors.text.inverse,
  },
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: radii.full,
    marginTop: 6,
  },
  statusPillDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  statusPillText: {
    fontSize: 11,
    fontFamily: typography.families.bold,
    color: colors.text.inverse,
  },
  vehiclePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(0, 0, 0, 0.18)',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: radii.lg,
    marginTop: 8,
  },
  vehiclePillText: {
    fontSize: 11,
    fontFamily: typography.families.extrabold,
    color: colors.text.inverse,
    letterSpacing: 0.5,
  },
  statsOverlap: {
    paddingHorizontal: spacing[4],
    marginTop: -20,
    zIndex: 20,
  },
  statsCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.bg.surface,
    borderRadius: radii['2xl'],
    paddingVertical: 14,
    paddingHorizontal: spacing[4],
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 4,
    borderWidth: 1,
    borderColor: colors.bg.subtle,
  },
  statCol: {
    flex: 1,
    alignItems: 'center',
    gap: 2,
  },
  statRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  statValue: {
    fontSize: 18,
    fontFamily: typography.families.black,
    color: colors.text.DEFAULT,
    fontVariant: ['tabular-nums'],
  },
  statLabel: {
    fontSize: 10,
    fontFamily: typography.families.extrabold,
    color: colors.text.subtle,
    letterSpacing: 0.5,
  },
  statDivider: {
    width: 1,
    height: 24,
    backgroundColor: colors.bg.subtle,
  },
  // Bloc de contact : une colonne, pas une rangée. Les boutons occupent toute
  // la largeur l'un sous l'autre — en rangée, ils se recroquevillaient à gauche.
  contactBlock: {
    paddingHorizontal: spacing[4],
    marginTop: spacing[4],
  },
  infoCard: {
    backgroundColor: colors.bg.surface,
    borderRadius: radii['2xl'],
    marginHorizontal: spacing[4],
    marginTop: spacing[4],
    padding: spacing[4],
    borderWidth: 1,
    borderColor: colors.bg.subtle,
  },
  infoTitle: {
    fontSize: 13,
    fontFamily: typography.families.extrabold,
    color: colors.text.DEFAULT,
    letterSpacing: 0.3,
    marginBottom: spacing[2],
  },
  zonesWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  zoneChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: radii.lg,
    backgroundColor: colors.primary[50],
  },
  zoneChipText: {
    fontSize: 11.5,
    fontFamily: typography.families.bold,
    color: colors.primary[700],
  },
  infoBody: {
    fontSize: 13,
    lineHeight: 20,
    color: colors.text.body,
  },
  reviewRow: {
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: colors.border.subtle,
  },
  reviewHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  reviewAuthor: {
    fontSize: 13,
    fontFamily: typography.families.bold,
    color: colors.text.DEFAULT,
  },
  reviewStars: {
    flexDirection: 'row',
    gap: 1,
  },
  reviewComment: {
    fontSize: 13,
    lineHeight: 19,
    color: colors.text.muted,
    marginTop: 4,
  },
});
