import { StyleSheet } from 'react-native';
import { colors, radii, spacing, typography } from '@daloa/ui';

export const loginStyles = StyleSheet.create({
  scrollContent: {
    flexGrow: 1,
    backgroundColor: colors.grey[50],
    paddingBottom: spacing[8],
  },
  curvedHeader: {
    paddingHorizontal: spacing[5],
    paddingTop: spacing[4],
    paddingBottom: 36,
    borderBottomLeftRadius: 36,
    borderBottomRightRadius: 36,
    alignItems: 'center',
    position: 'relative',
  },
  backBtn: {
    position: 'absolute',
    top: spacing[4],
    left: spacing[4],
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  logoBadge: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: colors.bg.surface,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing[3],
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 4,
  },
  headerTitle: {
    fontSize: 24,
    fontFamily: typography.families.extrabold,
    color: colors.text.inverse,
    marginBottom: 4,
  },
  headerSubtitle: {
    fontSize: 14,
    color: colors.primary[100],
    fontFamily: typography.families.medium,
  },
  formCard: {
    backgroundColor: colors.bg.surface,
    marginHorizontal: spacing[4],
    marginTop: -spacing[6],
    borderRadius: radii['2xl'],
    padding: spacing[5],
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 5,
    borderWidth: 1,
    borderColor: colors.bg.subtle,
  },
  errorBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: colors.status.errorLight,
    borderWidth: 1,
    borderColor: '#FEE2E2',
    borderRadius: radii.lg,
    padding: spacing[3],
    marginBottom: spacing[4],
  },
  errorText: {
    flex: 1,
    color: colors.status.errorDark,
    fontSize: 13,
    fontFamily: typography.families.medium,
  },
  googleBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    paddingVertical: 14,
    borderRadius: radii.xl,
    backgroundColor: colors.bg.surface,
    borderWidth: 1.5,
    borderColor: colors.border.DEFAULT,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
  },
  googleBtnText: {
    fontSize: 15,
    fontFamily: typography.families.semibold,
    color: colors.text.body,
  },
  dividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginVertical: spacing[4],
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: colors.border.DEFAULT,
  },
  dividerText: {
    fontSize: 12,
    color: colors.text.subtle,
    fontFamily: typography.families.medium,
  },
  forgotBtn: {
    alignSelf: 'flex-end',
    marginTop: spacing[2],
    marginBottom: spacing[4],
    paddingVertical: spacing[1],
  },
  forgotText: {
    fontSize: 13,
    fontFamily: typography.families.semibold,
    color: colors.primary[700],
  },
  registerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: spacing[5],
    flexWrap: 'wrap',
  },
  registerText: {
    fontSize: 13,
    color: colors.text.muted,
  },
  registerLink: {
    fontSize: 13,
    fontFamily: typography.families.bold,
    color: colors.primary[700],
  },
});
