import { StyleSheet } from 'react-native';
import { colors, radii, spacing, typography } from '@daloa/ui';

export const registrationStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.grey[50],
  },
  centerContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scrollContent: {
    padding: spacing[4],
    paddingBottom: spacing[6],
  },
  errorBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#FEE2E2',
    padding: 12,
    borderRadius: radii.md,
    marginBottom: spacing[4],
    borderWidth: 1,
    borderColor: colors.status.errorBorder,
  },
  errorText: {
    flex: 1,
    color: '#991B1B',
    fontSize: 13,
    fontFamily: typography.families.medium,
  },
  card: {
    backgroundColor: colors.bg.surface,
    borderRadius: radii.xl,
    padding: spacing[5],
    borderWidth: 1,
    borderColor: colors.bg.subtle,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  navRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: spacing[5],
  },
  backBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 14,
    borderRadius: radii.lg,
    backgroundColor: colors.bg.surface,
    borderWidth: 1,
    borderColor: colors.border.DEFAULT,
  },
  backBtnText: {
    fontSize: 15,
    fontFamily: typography.families.semibold,
    color: colors.text.body,
  },
  nextBtn: {
    flex: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 14,
    borderRadius: radii.lg,
    backgroundColor: colors.primary.DEFAULT,
  },
  nextBtnText: {
    fontSize: 15,
    fontFamily: typography.families.bold,
    color: colors.text.inverse,
  },
  submitBtn: {
    flex: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: radii.lg,
    backgroundColor: colors.status.success,
  },
  submitBtnText: {
    fontSize: 15,
    fontFamily: typography.families.bold,
    color: colors.text.inverse,
  },
  btnDisabled: {
    opacity: 0.45,
  },
  footerRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: spacing[6],
  },
  footerText: {
    fontSize: 14,
    color: colors.text.muted,
  },
  loginLink: {
    fontSize: 14,
    fontFamily: typography.families.bold,
    color: colors.primary.DEFAULT,
  },
});
